// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: helper/v1/envelope.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageKind int32

const (
	MessageKind_MESSAGE_KIND_UNSPECIFIED        MessageKind = 0
	MessageKind_MESSAGE_KIND_HANDSHAKE_REQUEST  MessageKind = 1
	MessageKind_MESSAGE_KIND_HANDSHAKE_RESPONSE MessageKind = 2
	MessageKind_MESSAGE_KIND_STATUS_REQUEST     MessageKind = 3
	MessageKind_MESSAGE_KIND_STATUS_RESPONSE    MessageKind = 4
	MessageKind_MESSAGE_KIND_SHUTDOWN_REQUEST   MessageKind = 5
	MessageKind_MESSAGE_KIND_SHUTDOWN_RESPONSE  MessageKind = 6
	MessageKind_MESSAGE_KIND_ERROR              MessageKind = 7
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "MESSAGE_KIND_UNSPECIFIED",
		1: "MESSAGE_KIND_HANDSHAKE_REQUEST",
		2: "MESSAGE_KIND_HANDSHAKE_RESPONSE",
		3: "MESSAGE_KIND_STATUS_REQUEST",
		4: "MESSAGE_KIND_STATUS_RESPONSE",
		5: "MESSAGE_KIND_SHUTDOWN_REQUEST",
		6: "MESSAGE_KIND_SHUTDOWN_RESPONSE",
		7: "MESSAGE_KIND_ERROR",
	}
	MessageKind_value = map[string]int32{
		"MESSAGE_KIND_UNSPECIFIED":        0,
		"MESSAGE_KIND_HANDSHAKE_REQUEST":  1,
		"MESSAGE_KIND_HANDSHAKE_RESPONSE": 2,
		"MESSAGE_KIND_STATUS_REQUEST":     3,
		"MESSAGE_KIND_STATUS_RESPONSE":    4,
		"MESSAGE_KIND_SHUTDOWN_REQUEST":   5,
		"MESSAGE_KIND_SHUTDOWN_RESPONSE":  6,
		"MESSAGE_KIND_ERROR":              7,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_helper_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_helper_v1_envelope_proto_enumTypes[0]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope is one private helper protocol message. Framing is defined in
// docs/protocol/helper-v1.md; this message never crosses renderer IPC.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	Kind          MessageKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=talos_pilot.helper.v1.MessageKind" json:"kind,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     *string                `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	OperationId   *string                `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3,oneof" json:"operation_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_HandshakeRequest
	//	*Envelope_HandshakeResponse
	//	*Envelope_StatusRequest
	//	*Envelope_StatusResponse
	//	*Envelope_ShutdownRequest
	//	*Envelope_ShutdownResponse
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_helper_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *Envelope) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_MESSAGE_KIND_UNSPECIFIED
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *Envelope) GetOperationId() string {
	if x != nil && x.OperationId != nil {
		return *x.OperationId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeRequest); ok {
			return x.HandshakeRequest
		}
	}
	return nil
}

func (x *Envelope) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *Envelope) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

func (x *Envelope) GetStatusResponse() *StatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StatusResponse); ok {
			return x.StatusResponse
		}
	}
	return nil
}

func (x *Envelope) GetShutdownRequest() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShutdownRequest); ok {
			return x.ShutdownRequest
		}
	}
	return nil
}

func (x *Envelope) GetShutdownResponse() *ShutdownResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShutdownResponse); ok {
			return x.ShutdownResponse
		}
	}
	return nil
}

func (x *Envelope) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_HandshakeRequest struct {
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,10,opt,name=handshake_request,json=handshakeRequest,proto3,oneof"`
}

type Envelope_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,11,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type Envelope_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,12,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

type Envelope_StatusResponse struct {
	StatusResponse *StatusResponse `protobuf:"bytes,13,opt,name=status_response,json=statusResponse,proto3,oneof"`
}

type Envelope_ShutdownRequest struct {
	ShutdownRequest *ShutdownRequest `protobuf:"bytes,14,opt,name=shutdown_request,json=shutdownRequest,proto3,oneof"`
}

type Envelope_ShutdownResponse struct {
	ShutdownResponse *ShutdownResponse `protobuf:"bytes,15,opt,name=shutdown_response,json=shutdownResponse,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ProtocolError `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

func (*Envelope_HandshakeRequest) isEnvelope_Payload() {}

func (*Envelope_HandshakeResponse) isEnvelope_Payload() {}

func (*Envelope_StatusRequest) isEnvelope_Payload() {}

func (*Envelope_StatusResponse) isEnvelope_Payload() {}

func (*Envelope_ShutdownRequest) isEnvelope_Payload() {}

func (*Envelope_ShutdownResponse) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type HandshakeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor         uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ExpectedBuildIdentity string                 `protobuf:"bytes,2,opt,name=expected_build_identity,json=expectedBuildIdentity,proto3" json:"expected_build_identity,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_helper_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HandshakeRequest) GetExpectedBuildIdentity() string {
	if x != nil {
		return x.ExpectedBuildIdentity
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	BuildIdentity string                 `protobuf:"bytes,2,opt,name=build_identity,json=buildIdentity,proto3" json:"build_identity,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_helper_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HandshakeResponse) GetBuildIdentity() string {
	if x != nil {
		return x.BuildIdentity
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_helper_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentity string                 `protobuf:"bytes,1,opt,name=build_identity,json=buildIdentity,proto3" json:"build_identity,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_helper_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetBuildIdentity() string {
	if x != nil {
		return x.BuildIdentity
	}
	return ""
}

func (x *StatusResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_helper_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{5}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_helper_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{6}
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	SafeMessage   string                 `protobuf:"bytes,2,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_helper_v1_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_helper_v1_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_helper_v1_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProtocolError) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

func (x *ProtocolError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_helper_v1_envelope_proto protoreflect.FileDescriptor

const file_helper_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18helper/v1/envelope.proto\x12\x15talos_pilot.helper.v1\"\xda\x06\n" +
	"\bEnvelope\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x126\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".talos_pilot.helper.v1.MessageKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\"\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tH\x01R\tsessionId\x88\x01\x01\x12&\n" +
	"\foperation_id\x18\x05 \x01(\tH\x02R\voperationId\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12V\n" +
	"\x11handshake_request\x18\n" +
	" \x01(\v2'.talos_pilot.helper.v1.HandshakeRequestH\x00R\x10handshakeRequest\x12Y\n" +
	"\x12handshake_response\x18\v \x01(\v2(.talos_pilot.helper.v1.HandshakeResponseH\x00R\x11handshakeResponse\x12M\n" +
	"\x0estatus_request\x18\f \x01(\v2$.talos_pilot.helper.v1.StatusRequestH\x00R\rstatusRequest\x12P\n" +
	"\x0fstatus_response\x18\r \x01(\v2%.talos_pilot.helper.v1.StatusResponseH\x00R\x0estatusResponse\x12S\n" +
	"\x10shutdown_request\x18\x0e \x01(\v2&.talos_pilot.helper.v1.ShutdownRequestH\x00R\x0fshutdownRequest\x12V\n" +
	"\x11shutdown_response\x18\x0f \x01(\v2'.talos_pilot.helper.v1.ShutdownResponseH\x00R\x10shutdownResponse\x12<\n" +
	"\x05error\x18\x10 \x01(\v2$.talos_pilot.helper.v1.ProtocolErrorH\x00R\x05errorB\t\n" +
	"\apayloadB\r\n" +
	"\v_session_idB\x0f\n" +
	"\r_operation_id\"q\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x126\n" +
	"\x17expected_build_identity\x18\x02 \x01(\tR\x15expectedBuildIdentity\"\x85\x01\n" +
	"\x11HandshakeResponse\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0ebuild_identity\x18\x02 \x01(\tR\rbuildIdentity\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x0f\n" +
	"\rStatusRequest\"[\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0ebuild_identity\x18\x01 \x01(\tR\rbuildIdentity\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"d\n" +
	"\rProtocolError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fsafe_message\x18\x02 \x01(\tR\vsafeMessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*\x96\x02\n" +
	"\vMessageKind\x12\x1c\n" +
	"\x18MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMESSAGE_KIND_HANDSHAKE_REQUEST\x10\x01\x12#\n" +
	"\x1fMESSAGE_KIND_HANDSHAKE_RESPONSE\x10\x02\x12\x1f\n" +
	"\x1bMESSAGE_KIND_STATUS_REQUEST\x10\x03\x12 \n" +
	"\x1cMESSAGE_KIND_STATUS_RESPONSE\x10\x04\x12!\n" +
	"\x1dMESSAGE_KIND_SHUTDOWN_REQUEST\x10\x05\x12\"\n" +
	"\x1eMESSAGE_KIND_SHUTDOWN_RESPONSE\x10\x06\x12\x16\n" +
	"\x12MESSAGE_KIND_ERROR\x10\aBQZOgithub.com/agiledevel/talos-pilot/helper/internal/protocol/helper/v1;protocolv1b\x06proto3"

var (
	file_helper_v1_envelope_proto_rawDescOnce sync.Once
	file_helper_v1_envelope_proto_rawDescData []byte
)

func file_helper_v1_envelope_proto_rawDescGZIP() []byte {
	file_helper_v1_envelope_proto_rawDescOnce.Do(func() {
		file_helper_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helper_v1_envelope_proto_rawDesc), len(file_helper_v1_envelope_proto_rawDesc)))
	})
	return file_helper_v1_envelope_proto_rawDescData
}

var file_helper_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_helper_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_helper_v1_envelope_proto_goTypes = []any{
	(MessageKind)(0),          // 0: talos_pilot.helper.v1.MessageKind
	(*Envelope)(nil),          // 1: talos_pilot.helper.v1.Envelope
	(*HandshakeRequest)(nil),  // 2: talos_pilot.helper.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 3: talos_pilot.helper.v1.HandshakeResponse
	(*StatusRequest)(nil),     // 4: talos_pilot.helper.v1.StatusRequest
	(*StatusResponse)(nil),    // 5: talos_pilot.helper.v1.StatusResponse
	(*ShutdownRequest)(nil),   // 6: talos_pilot.helper.v1.ShutdownRequest
	(*ShutdownResponse)(nil),  // 7: talos_pilot.helper.v1.ShutdownResponse
	(*ProtocolError)(nil),     // 8: talos_pilot.helper.v1.ProtocolError
}
var file_helper_v1_envelope_proto_depIdxs = []int32{
	0, // 0: talos_pilot.helper.v1.Envelope.kind:type_name -> talos_pilot.helper.v1.MessageKind
	2, // 1: talos_pilot.helper.v1.Envelope.handshake_request:type_name -> talos_pilot.helper.v1.HandshakeRequest
	3, // 2: talos_pilot.helper.v1.Envelope.handshake_response:type_name -> talos_pilot.helper.v1.HandshakeResponse
	4, // 3: talos_pilot.helper.v1.Envelope.status_request:type_name -> talos_pilot.helper.v1.StatusRequest
	5, // 4: talos_pilot.helper.v1.Envelope.status_response:type_name -> talos_pilot.helper.v1.StatusResponse
	6, // 5: talos_pilot.helper.v1.Envelope.shutdown_request:type_name -> talos_pilot.helper.v1.ShutdownRequest
	7, // 6: talos_pilot.helper.v1.Envelope.shutdown_response:type_name -> talos_pilot.helper.v1.ShutdownResponse
	8, // 7: talos_pilot.helper.v1.Envelope.error:type_name -> talos_pilot.helper.v1.ProtocolError
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_helper_v1_envelope_proto_init() }
func file_helper_v1_envelope_proto_init() {
	if File_helper_v1_envelope_proto != nil {
		return
	}
	file_helper_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_HandshakeRequest)(nil),
		(*Envelope_HandshakeResponse)(nil),
		(*Envelope_StatusRequest)(nil),
		(*Envelope_StatusResponse)(nil),
		(*Envelope_ShutdownRequest)(nil),
		(*Envelope_ShutdownResponse)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helper_v1_envelope_proto_rawDesc), len(file_helper_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_helper_v1_envelope_proto_goTypes,
		DependencyIndexes: file_helper_v1_envelope_proto_depIdxs,
		EnumInfos:         file_helper_v1_envelope_proto_enumTypes,
		MessageInfos:      file_helper_v1_envelope_proto_msgTypes,
	}.Build()
	File_helper_v1_envelope_proto = out.File
	file_helper_v1_envelope_proto_goTypes = nil
	file_helper_v1_envelope_proto_depIdxs = nil
}
